### ISSUE TITLE
Namenodes break after restarting

### ISSUE THREAD

**Issue by nightkr** [stackabletech/hdfs-operator#153]
### Affected version

KRB5 spike based on 0.3.0 (note to self: triage and validate against trunk)

### Current and expected behavior

Namenodes keep crashing after deleting their pods, complaining about mismatching transaction IDs.

I suspect this is either related to the eager attempts to reformat them ending with corrupted data, or some data that is being persisted outside of stored volumes.

### Environment

GKE with k8s 1.22

**Comment by maltesander** [comment]
Im currently fixing (https://github.com/stackabletech/hdfs-operator/issues/147) this and reworking the whole formatting thing. This should be resolved after that as well.
