### ISSUE TITLE
Allow external access to the HDFS cluster

### ISSUE THREAD

**Issue by nightkr** [stackabletech/hdfs-operator#174]
Currently we just expose overlay network addresses in both hdfs-site.xml and dynamic registrations to the namenodes. This prevents users from accessing HDFS from outside of the k8s overlay network.

This requires:
 
- Namenodes must be accessed using stable addresses (such as a `LoadBalancer` `Service` where available)
  - The generated discovery profile must be altered to use this address
- Datanodes must be accessed using their associated `NodePort` `Service` addresses

Datanode addresses cannot currently be overridden in HDFS, I have outlined the changes required for this in https://github.com/stackabletech/hadoop/tree/spike/override-datanode-id. This is a purely server-side change.

I have a spike that implements this semi-manually in https://github.com/stackabletech/hdfs-operator/tree/spike/external-access, if we consider that access pattern acceptable then we can start looking into how to integrate it better into both HDFS and the operator.

**Comment by soenkeliebau** [comment]
I have created a sister issue to this one #235 which we can use to track the upstream work to properly fix this. 
For this issue I think we should simply shoot for patching the version of HDFS that we ship, as timelines around upstream work can be completely unpredictable.

**Comment by fhennig** [comment]
@lfrancke This is on the engineering board so we can remove it from the epic board (it isn't an epic). right?

**Comment by lfrancke** [comment]
The docs for this are available at: https://docs.stackable.tech/home/nightly/hdfs/usage-guide/listenerclass

**Comment by lfrancke** [comment]
I think the docs should have a note (at the page linked above) saying that the Listener operator is required for this feature.

Could you add that please?

**Comment by nightkr** [comment]
It's already listed in https://docs.stackable.tech/home/nightly/hdfs/getting_started/installation as a platform-wide dependency.

I don't think it makes sense to think of it as a "feature dependency", list-op also replaces the in-cluster service discovery used previously and is a hard dependency for hdfs-op.

**Comment by nightkr** [comment]
That said, perhaps this highlights that we should also call out the list-op dependency in the changelog?

**Comment by lfrancke** [comment]
Thanks.
At some point we should have something that calls out "dependencies" or "requirements"
That's at least what I always search for in new products. Here it's listend in a paragraph under Installation. The discovery could be better

ping @fhennig  for opinions
