### ISSUE TITLE
Allow enabling secure mode with Kerberos on HDFS

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/hdfs-operator#178]
As a user/admin I'd like to be able to enable secure mode in HDFS using Kerberos so I can authenticate all requests against HDFS.

This is done when
- [x] a CRD change(s) has been proposed and reviewed on how to enable Kerberos
- [x] it uses the functionality provided by the secret operator to provision Kerberos keytabs https://github.com/stackabletech/secret-operator/issues/4
- [x] documentation is added
- [x] integration tests are added
- [ ] examples are added
- [x] feature tracker is updated

**Comment by sbernauer** [comment]
Would be great if someone with hdfs and Kerberos expertise could have a look at the current state

**Comment by sbernauer** [comment]
Tests finally passed on Azure
Waiting for review from an HDFS + Kerberos expert if possible :)
