### ISSUE TITLE
Namenodes deadlock in safemode when all namenodes have been down at the same time

### ISSUE THREAD

**Issue by nightkr** [stackabletech/hdfs-operator#264]
Because we set `dfs.ha.nn.not-become-active-in-safemode`, each namenode starts in safemode until it has:

1. Verified some amount of datanode blocks
2. Downloaded the latest fsimage from another active namenode

If all namenodes go down at the same time then condition 2 will never be met, since there is no active namenode to synchronize with.

Unsetting `dfs.ha.nn.not-become-active-in-safemode` fixes this by allowing a safemode NN to take over, but the implications of this should probably be investigated by someone more familiar with HDFS first. Presumably we set it for a reason in the first place.

**Comment by lfrancke** [comment]
This was set by accident at the very beginning of our operator due to a misinterpretation of the [docs](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithNFS.html) of HDFS.
