### ISSUE TITLE
Add support for HDFS rack awareness feature

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/hdfs-operator#325]
We should add support for HDFS' rack awareness feature to the HDFS operator.

This cannot be achieved via config overrides, as the config setting takes a script which has to return the rack based on hostname and ip address of the datanode.

Some ideas that have been put forward for this are: 

1. Ship kubectl with the hdfs image and do something like this: 
`kubectl get node $(kubectl get pod <hostname> -o yaml | jq ".status.node") -o yaml | yq ''.metadata.labels."[kubernetes.io/rack](http://kubernetes.io/rack)
`
2. Mount a configmap in the namenode somewhere and have a fixed script configured that does a lookup in a textfile in that configmap. This configmap could then be updated by the hdfs operator.
3. Have a sidecar-container in the hdfs namenode that periodically polls the racks of the datanodes and writes that into a shared emptyDir. That emptyDir can be easily used by the main container
```[tasklist]
### Tasks
- [ ] documentation for the feature needs to be added
```

**Comment by lfrancke** [comment]
Is there documentation for this? If so: Can you link it here please?

**Comment by adwk67** [comment]
https://docs.stackable.tech/home/nightly/hdfs/usage-guide/operations/rack-awareness
