### ISSUE TITLE
Implement Group Mapper

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/hdfs-operator#401]
PR: https://github.com/stackabletech/hdfs-group-mapper/pull/1

HDFS internally uses user groups for group permissions on folders etc. For this reason it is not enough to just have the groups in OPA during authorization, but they actually need to be available to Hadoop.
Hadoop offers a few default group providers
- LDAP
- Linux user group (usually provided by SSSD or Centrify or similar tools)

To allow extending this model Hadoop has an [interface](https://github.com/apache/hadoop/blob/86c28f063900d091b4427b35eccff95b8f8db1cb/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/GroupMappingServiceProvider.java#L33) that users can implement to provide user to group mappings.

We need an implementation of this interface to talk to Opa/UIF and provide the groups resolved there. 

```[tasklist]
### Clarifications
- [x] which hadoop versions? Just latest, or do we need to provide support for multiple versions? Yes: mutiple HDFS versions should be supported. See https://github.com/stackabletech/docker-images/blob/main/hadoop/Dockerfile
- [x] does this interface impl basically provide what can be set statically in `hadoop.user.group.static.mapping.overrides`? See https://github.com/apache/hadoop/blob/86c28f063900d091b4427b35eccff95b8f8db1cb/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/LdapGroupsMapping.java#L510
- [x] Don't double cache
- [x] UIF API: is this ReST? Yes, but indirectly: address an OPA rule via the OPA service that returns whatever group info UIF has fetched via loopback. Will need a config value to discover OPA.
- [x] Return format: a list of strings?
```

**Comment by adwk67** [comment]
Docs: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/GroupsMapping.html

**Comment by sbernauer** [comment]
It would be great if we could think about the API between Hadoop -> OPA and present the result in Arch meeting.
In case you are interested I would be happy to have a chat today so that you can be present it in Arch meeting tomorrow - but this is just an offer, feel free to do whatever you'd like ;)
