### ISSUE TITLE
Reintroduce dummy `.spec.clusterConfig.listenerClass`

### ISSUE THREAD

**Issue by nightkr** [stackabletech/hdfs-operator#461]
There was only one valid value, but some of our tests and examples try to set it explicitly. After some discussion we agreed to add it back as a dummy field for now.

Regressed in #450, reported at https://stackable-workspace.slack.com/archives/C031A56R127/p1706516386716159.

**Comment by lfrancke** [comment]
Can you elaborate what the future of this is?

Do we want to remove this field in the next version or will it stay around forever?

**Comment by nightkr** [comment]
It should be dropped in v1alpha2.

**Comment by lfrancke** [comment]
@sbernauer Could you add this to your tracking issue for future changes?

**Comment by sbernauer** [comment]
It already is on https://github.com/stackabletech/issues/issues/504 - It was actually the trigger for me to create it :)
