### ISSUE TITLE
Metrics with specific suffixes are renamed or not exported at all

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/hdfs-operator#634]
### Affected Stackable version

24.7.0, 24.11.0

### Affected Apache HDFS version

3.3.4, 3.3.6

### Current and expected behavior

For instance, the suffix `_created` of the metric `hadoop_namenode_files_created` is removed and the metric is named now `hadoop_namenode_files`. The suffix `_total` of the metric `hadoop_namenode_files_total` is also removed but as the metric `hadoop_namenode_files` already exists, it is discarded.

### Possible solution

Update the JMX exporter rules to match the used JMX exporter version.

### Additional context

The JMX exporter 1.0.1+ conforms with OpenMetrics (https://github.com/prometheus/jmx_exporter/releases/tag/1.0.1) and removes reserved suffixes.

### Would you like to work on fixing this bug?

yes

# Tasks

- [x] stackabletech/docker-images#962
- [x] #635

**Comment by siegfriedweber** [comment]
# Release Notes

## Bugfixes

* HDFS: Metrics suffixed with `_total`, e.g. `hadoop_namenode_files_total`, are emitted again. Metrics originally suffixed with `_created` and `_info` are now suffixed with `_created_` and `_info_` to be OpenMetrics compliant.

**Comment by lfrancke** [comment]
Is this going to be in 24.11.1?

**Comment by siegfriedweber** [comment]
> Is this going to be in 24.11.1?

No, because this would break the behavior of 24.11.0 and a patch release should not contain breaking changes.

I hope, that this will be fixed soon on upstream (https://github.com/prometheus/jmx_exporter/issues/982#issuecomment-2523517695).
